"""Firsst

Revision ID: 105f5c0b2eb9
Revises: 53ee2dc9e7b8
Create Date: 2024-08-23 20:42:55.152344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105f5c0b2eb9'
down_revision: Union[str, None] = '53ee2dc9e7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
