"""Booking model

Revision ID: 46b1916056a6
Revises: c6ff6bc63960
Create Date: 2024-08-23 21:03:20.971415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b1916056a6'
down_revision: Union[str, None] = 'c6ff6bc63960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
