"""empty message

Revision ID: 53ee2dc9e7b8
Revises: f87e9c0f2145
Create Date: 2024-08-17 12:54:27.458086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53ee2dc9e7b8'
down_revision: Union[str, None] = 'f87e9c0f2145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('register_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('room_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('register_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='User_room_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='User_pkey')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###
