"""empty message

Revision ID: d6b55b9f9454
Revises: 46b1916056a6
Create Date: 2024-08-23 22:02:46.199861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b55b9f9454'
down_revision: Union[str, None] = '46b1916056a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column(sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'hotel', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'room_id')
    # ### end Alembic commands ###
